# Generated by Django 5.2.8 on 2025-11-17 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0002_supplier_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='product_attachments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attachments', to='scp.product'),
        ),
    ]
