# Generated by Django 5.2.8 on 2025-11-17 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0003_alter_productattachment_file_and_more'),
    ]

    operations = [
        # 1. Add the new fields first (nullable for now)
        migrations.AddField(
            model_name='conversation',
            name='consumer_contact',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='conversations',
                to='scp.consumercontact'
            ),
        ),
        migrations.AddField(
            model_name='conversation',
            name='supplier_staff',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='conversations',
                to='scp.supplierstaffmembership'
            ),
        ),
        # 3. Alter unique_together last, after fields exist
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('supplier_staff', 'consumer_contact')},
        ),
    ]
