# Generated by Django 5.2.8 on 2025-11-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0004_alter_conversation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='consumer',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='supplier',
        ),
    ]
