# Generated by Django 5.2.8 on 2025-11-19 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0005_remove_conversation_consumer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='scp.complaint'),
        ),
    ]
