# Generated by Django 5.2.8 on 2025-11-19 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0006_conversation_complaint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='consumer_contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='scp.consumercontact'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='supplier_staff',
        ),
        migrations.AddField(
            model_name='conversation',
            name='supplier_staff',
            field=models.ManyToManyField(blank=True, null=True, related_name='conversations', to='scp.supplierstaffmembership'),
        ),
    ]
