# Generated by Django 5.2.8 on 2025-11-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0007_alter_conversation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='supplier_staff',
            field=models.ManyToManyField(blank=True, related_name='conversations', to='scp.supplierstaffmembership'),
        ),
    ]
