# Generated by Django 5.2.8 on 2025-11-19 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0008_alter_conversation_supplier_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='escalated_at',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='escalated_to',
        ),
    ]
