# Generated by Django 5.2.8 on 2025-11-20 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0009_remove_complaint_escalated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
